apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drivethru-manager
rules:
  - apiGroups: ["drivethru.notjustanna.net"]
    resources: ["staticsites"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["drivethru.notjustanna.net"]
    resources: ["staticsites/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["drivethru.notjustanna.net"]
    resources: ["staticsites/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
